// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnGHpQx6GRdiz8WjRjmsGUWsvk0gtTMPw',
    appId: '1:787780064793:android:5a1f7eeb987f0f9ac33c88',
    messagingSenderId: '787780064793',
    projectId: 'sayhi-7baeb',
    databaseURL: 'https://sayhi-7baeb-default-rtdb.firebaseio.com',
    storageBucket: 'sayhi-7baeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsekV6f6sI0jV-oW1SPS_dfj9bbsxJ5bg',
    appId: '1:787780064793:ios:cc0450f243ec4f84c33c88',
    messagingSenderId: '787780064793',
    projectId: 'sayhi-7baeb',
    databaseURL: 'https://sayhi-7baeb-default-rtdb.firebaseio.com',
    storageBucket: 'sayhi-7baeb.appspot.com',
    androidClientId: '787780064793-u5uv6equan95fncr65s83afff07l5rbe.apps.googleusercontent.com',
    iosClientId: '787780064793-nqjbtv3f2no80jm578dmnaefgtf0cnbp.apps.googleusercontent.com',
    iosBundleId: 'com.jasspj.sayhi',
  );
}
